### ISSUE TITLE
Really strange error with tor browser??? 

### ISSUE THREAD

**Issue by Infcodes** [efenatuyo/xool#4]
![image](https://github.com/user-attachments/assets/4088bfee-a89e-4f4f-92ca-6bd0671d0a67)
I actually have no idea whats going on right now

**Comment by efenatuyo** [comment]
this error is by tor saying that the port 9080 is already used by another software. You have to terminate the program that uses the port

**Comment by Infcodes** [comment]
> t

Do you know how I can fix this?

**Comment by Infcodes** [comment]
I fixed that, Now I have a new error any ideas? 
![image (1)](https://github.com/user-attachments/assets/e6e45395-f39b-4978-893e-f493c9ef7725)
